version: "2"

services:
  prepaid-svc:
    image: richardcase/casecardgo-prepaidsvc
    networks:
      - backend
    depends_on:
      - nats
      - mongo
  
  projection-svc:
    image: richardcase/casecardgo-projsvc
    networks:
      - backend
      - frontend
    depends_on:
      - nats
      - mongo

  nats:
    image: nats
    ports: 
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
  frontend: