# Build stage
FROM golang:1.9 as builder
WORKDIR /go/src/github.com/richardcase/casecardgo
ADD . .
RUN make setup && make build-prod

# Final Stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates

COPY --from=builder /go/src/github.com/richardcase/casecardgo/prepaid-svc /app/prepaid-svc
ENTRYPOINT /app/prepaid-svc

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.name="CaseCardGo - Prepaid Account Service" \
    org.label-schema.description="A service to implement a prepaid card account" \
    org.label-schema.url="https://github.com/richardcase/casecardgo" \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-url="https://github.com/richardcase/casecardgo" \
    org.label-schema.vendor="Richard Case" \
    org.label-schema.version=$VERSION \
    org.label-schema.schema-version="1.0"