version: "3"

services:
  prepaid-svc:
    image: richardcase/casecardgo-prepaidsvc:latest
    entrypoint:
      - /app/prepaid-svc
      - -mongourl 
      - mongo:27017
      - -natsurl 
      - nats://nats:4222
      - -alsologtostderr
      - -stderrthreshold 
      - INFO
      - -v
      - "2"
    ports:
      - "8080:8080"
    depends_on:
      - nats
      - mongo
  
  projection-svc:
    image: richardcase/casecardgo-projsvc:latest
    entrypoint:
      - /app/prepaid-projector
      - -mongourl 
      - mongo:27017
      - -natsurl 
      - nats://nats:4222
      - -alsologtostderr
      - -stderrthreshold 
      - INFO
      - -v
      - "2"
    ports:
      - "8081:8081"
    depends_on:
      - nats
      - mongo

  nats:
    image: nats
    ports: 
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  mongo:
    image: mongo
    ports:
      - "27017:27017"