FROM scratch
ADD prepaid-svc /
ENTRYPOINT ["/prepaid-svc"]

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.name="CaseCardGo - Prepaid Account Service" \
    org.label-schema.description="A service to implement a prepaid card account" \
    org.label-schema.url="https://github.com/richardcase/casecardgo" \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-url="https://github.com/richardcase/casecardgo" \
    org.label-schema.vendor="Richard Case" \
    org.label-schema.version=$VERSION \
    org.label-schema.schema-version="1.0"